package LaskinFx.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END
import LaskinFx.*;

/**
 * Test class made by ComTest
 * @version 2021.08.11 21:28:54 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class laskinControllerTest {



  // Generated by ComTest BEGIN
  /** testKasitteleNumerot86 */
  @Test
  public void testKasitteleNumerot86() {    // laskinController: 86
    int i = 0; 
    assertEquals("From: laskinController line: 88", 0, i); 
  } // Generated by ComTest END
}